### ISSUE TITLE
Safe default for HttpClient

### ISSUE THREAD

**Issue by judedaryl** [FantasticFiasco/serilog-sinks-http#101]
**Is your feature request related to a problem? Please describe.**
As stated in the [microsoft docs](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netcore-3.1)

> HttpClient is intended to be instantiated once and re-used throughout the life of an application. Instantiating an HttpClient class for every request will exhaust the number of sockets available under heavy loads. This will result in SocketException errors. Below is an example using HttpClient correctly.

**Describe the solution you'd like**
Use IHttpClientFactory to implement the default HttpClient which is only available in the DI using services.AddHttpClient (for .NET Core)

**Describe alternatives you've considered**
Using a lighter version of HttpClientFactory that does not require DI

**Additional context**

**Comment by FantasticFiasco** [comment]
We've all been burned by `HttpClient`, at least once in our career :-)

But please correct me if I'm wrong, but I don't think this code is misusing the class. It's only instantiated once, when the sink is created, and that instance is reused during the application lifetime. Are you of a different mind? Do you foresee us exhausting the numbers of sockets?

Regarding the usage of `IHttpClientFactory`. It's a great class with performance improvements and lets us centralize configuration of HTTP clients, mostly currently most used in web servers. My problem with it is that it only is available for .NET Core 2.1 and above. That's troublesome for a library developer because I have to support older versions of .NET. Do you know of any NuGet packages making this functionality working for older versions of .NET, like a polyfill? That would make me consider the change.

**Comment by FantasticFiasco** [comment]
Close due to inactivity.
