### ISSUE TITLE
Is it possible to change the url hostname on runtime?

### ISSUE THREAD

**Issue by smartaquarius10** [FantasticFiasco/serilog-sinks-http#157]
Hello,

I have a situation where I want to enable this log only on requirement basis and call a new webhook. Is it possible to make the hostname configurable. I'm hosting my api in azure so
1. I can set the host name in azure app settings or,
2. Call a controller end point by sending the hostname in request and manually update at runtime

I will control this http logger through LoggingLevelSwitch. The only issue I'm facing is how to update the hostname on runtime because that webhook is not fix. 

Please help. I can't put this query on stackoverflow because my access is barred due to some downvotes on my old questions.

Thank you

**Comment by FantasticFiasco** [comment]
Hi @smartaquarius10!

Let's first make sure that I understand the use case. By default you don't want to send any log event over the network, but then something happens and you are updating the logging level switch to start sending events, but since the webhook doesn't have a fixed URL, you would get the log server URL from somewhere, e.g. Azure or whatever. Is this correct?

It's not that you by default are sending events to one log server, and then with some magic with the logging level switch wish to send the log events to another log server?

**Comment by smartaquarius10** [comment]
Correct. Actually, I am hosting my .net core application in azure in which I have 2 types of logs 
1. Trace logs
2. Exception logs

I shall log exceptions using serilog file sink but for console logs we don’t have anything in azure Like kubernetes unless we pay for log stream storage. 

I already have kubernetes instance where I can host an api as a webhook receiver to which I can send my trace logs. But, as u understood correct its url is not fix and once my troubleshooting is complete I will delete my webhook api and change the log switch. 

Now, the next time I host my api again in kubernetes, for logs collection, its url will change. In this case it is very difficult to update the url again in .net Core api in azure and restart it. 

Is there anyway to change the url on runtime.

**Comment by FantasticFiasco** [comment]
No, there isn't any way to change the URL in runtime. It's also something that I'd rather not implement in this library. To me this falls in the same ballpark as #134, it's a network problem, and thus should be solved using a network solution.

I'd have a gateway on the network with a fixed URL, with the option to configure this gateway to forward the trace events to your temporary webhook. Since you are living in Azure, you have [a multitude of gateways to chose from](https://docs.microsoft.com/azure/architecture/microservices/design/gateway#choosing-a-gateway-technology). To me this sounds like a better solution. What do you think?
