### ISSUE TITLE
Suggestion: Default durable files naming

### ISSUE THREAD

**Issue by Dissimilis** [FantasticFiasco/serilog-sinks-http#36]
By default durable buffer files are named "Buffer-{Date}.json" and "Buffer.bookmark"
I see two issues with that:
1. When using multiple loggers only one logger (which acquired lock on file) works because of the file name collision. This is not immediately apparent and digging into Serilog selflog is needed for "first timers". Not sure if this is solvable, but at least add a warning in readme.
2. Consider using  "Buffer-{Date}.log" and "Buffer.bookmark.log" default names instead. This would be compatible with most gitignore files.

I can change names to my liking, but it would be nice to have strong defaults.

**Comment by FantasticFiasco** [comment]
The file name is configurable, I've written some documentation about it [here](https://github.com/FantasticFiasco/serilog-sinks-http/wiki/Durable-HTTP-sink). Is this sufficient, or would you like something different?

**Comment by Dissimilis** [comment]
I have read the documentation. What I'm suggesting is to use better default file names.
Using ".log" extensions on both files would play well with most default .gitignore files.

**Comment by FantasticFiasco** [comment]
I've been heavily inspired by [Serilog.Sinks.Seq](https://github.com/serilog/serilog-sinks-seq), and they are using the `.bookmark` file extension. That's why I am using it.

I can think of arguments for and against the `.log` extension, but the arguments for does not have the value to cover the cost of introduce a breaking change i this sink and release a new major version.

I will leave the issue open a couple of days, if you can think of other arguments supporting your case, please tell me, and I will reconsider. Otherwise I will close the issue.

**Comment by Dissimilis** [comment]
I understand the reasons behind your arguments.  Probably, as you said, it's not a good idea to introduce this braking change.
