### ISSUE TITLE
Best practices for sending "debug data objects" to ELK stask

### ISSUE THREAD

**Issue by Dissimilis** [FantasticFiasco/serilog-sinks-http#39]
This is not strictly Serilog.Sinks.Http related, but many use this sink for writing to ELK so this might be a good place for discussion.

### Step 1: Describe your environment

ELK stask + Serilog with Http sink
  
### Step 2: Describe the problem

Elastic rejects documents when property name has different structure than already indexed document

#### Steps to reproduce:

logger.Information("MsgTest1 {@Payload}", new int[] { 1, 2, 3 });
logger.Information("MsgTest2 {@Payload}", new {Foo = new int[] { 1 }});
  
#### Observed results

Elastic search fails to save second event document, because already indexed Property.Payload type differs from second one.
Elastic error: _"mapper [Properties.Payload] of different type, current_type [long], merged_type [ObjectMapper]"_

This is serious issue when using vanilla ELK stask + Serilog.Sinks.Http across multiple developers/services. 
One developer logs something using generic parameter name, then second developer unknowingly tries to use same name, but different object type and his messages are not logged (almost silently dropped).

Possible solutions, as I see them:
1. Add this when configuring serilog: 	`.Destructure.ByTransformingWhere<object>((t)=>true,	(x)=>JsonConvert.SerializeObject(x, Newtonsoft.Json.Formatting.Indented))`
2. Add logstash filter which stringifies whole [Properties] object, something like this: `json_encode { source => "[Properties]" }`
3. Decide on a rule to always serialiaze complex anonymous objects yourself before passing then to serilog.
4. Write custom formatter for Http sink which would serialize all properties to strings (unstructuring them)
5. Extend Http sink to accept  property transformer. TextFormatter would be left as is, but http sink would use property formatter for serializing properties. This could look like serilog's: `ByTransformingWhere `. Do so could allow having custom prpoperties format for http sink, but keep the defaults for other sinks and message rendering.
6. Extend Http sink to accept simple param `bool StringifyProperties`. Or something more flexible: `Func<object, string> ParamsStrigifier`
7. Write Elastic dynamic template which treats everything in [Properties] as string. Like described here: http://blog.florian-hopf.de/2016/05/stringify-everything-elasticsearch.html

**Comment by Dissimilis** [comment]
Problems with my solutions:
1.  Removes the ability to add structured property, only simple values are allowed. Easy to forget when adding logging to new project.
2. Removes the ability to have any properties, while [Properties] object would be string in Elactic
3. Easy to forget, human factor. Ugly misuse of serilog: `logger.Information("{obj}", JsonConverter.SerilizeObject(obj, Formatting.Indented))`
4. Similar problems as number 1 (but only properties would be impacted, not rendering, like in number 1). Lots of code which should be shared across all projects.
5. Needs changes to Http sink. Results would be like with 4, but without writing own formatter.
6. Needs changes to Http sink.  But sounds like a simple solution :)
7. Haven't tested this, I don't have in depth knowledge of Elastic.

**Comment by FantasticFiasco** [comment]
I work on a product developed by many autonomous teams responsible for a multitude of micro services, all logging to the same Elastic Stack. I know the struggle is real when you discover that you are using the same property name as another service, but the structure of the value is different from their initial log event.

What we've done to cope with that is a variant of your 4. We've written a custom text formatter that has the concept of a _namespace_. The namespace is unique for the micro service and separates it from the other micro services. That way we can be sure to prevent clashes between services, but still have to be mindful of the structure of log events logged from one service, but that responsibility falls on the team responsible for the service and is "easily" handled.

Now back to the implementation. It would be a [event formatter](https://github.com/FantasticFiasco/serilog-sinks-http/wiki/Event-formatters) that in its constructor takes the micro service name, and optionally a sub-component name (a micro service can concise of many individual sub-components, each individually deployed). The micro service name and sub-component name would be concatenated into a namespace, and properties would be serialized into that namespace. As an example, lets say the micro service was called `Foo`, the event formatter would create a property called `Foo` in the log event JSON instead of creating the property called `Property`.

What do you think?

**Comment by Dissimilis** [comment]
First of all, do you see benefits in having each and every custom object destructured and indexed? On our team, 99% of time, we don't need to have complex objects indexed, any human readable string representing that object is good enough. Most of events send custom objects to use when manually investigating something.

I will respond to implementation suggestions tomorrow, timezone forces me to sleep :)

**Comment by FantasticFiasco** [comment]
Yes, I think the value of Serilog, and all other structured logging frameworks, is to keep the log event structured as long as possible.

I see structured logging and its properties as the fundament on which one configures alerts and notifications. I think these alerts and notifications are the trigger for manual investigation, and only at that point the rendered message becomes valuable.

I mean, if you only are interested in the textual representation, why even bother with structured log events?

I think you must be somewhere east of my position. Over here it is getting late, but I think I can muster another hour of development :-)

**Comment by Dissimilis** [comment]
I have some concerns about your namespaces proposal. As I understood, all properties would have namespaces? For example we use MachineName enricher, its path would change from `Properties.MarchineName` to `Namespace.MachineName`? There would be no common structure anymore. And if I'm not mistaken, it is impossible for sink to distinguish between enricher supplied value and passed when calling logger.

>if you only are interested in the textual representation, why even bother with structured log events?
I strongly disagree. Looks like you see it as black and white. I get a lot of benefits from using serilog, like message templates and great logging lib overall. But I also want to use serilog as simple debug logger for manual investigation. Serilog does'n say "Use me only if you want structured logging otherwise use NLog/Log4Net", Serilog says "Use me always and have benefit of having structured logging".




Looks like we live in similar timezone, I just respond from work, and you from home :)

**Comment by FantasticFiasco** [comment]
> ...it is impossible for sink to distinguish between enricher supplied value and passed when calling logger.

Yes that is correct. All properties would be placed under this unique namespace and there would be no common structure of log messages between micro services. That would not be a problem if each team was responsible for their log events, but is a big problem if you have a governing team that monitor all micro services.

>  I get a lot of benefits from using serilog...

And I hope you will continue to use it. I can do nothing but join you in your praises of Serilog, I would not devote my free time to a logging framework I didn't enjoy.

> But I also want to use serilog as simple debug logger for manual investigation...

Have you thought about using different sinks for different circumstances? I think one can categorize the existing sinks into two categories. The first category contain sinks that help in development, for instance the console sink or my UDP sink. The second category contain sinks that provide value in production, and I strongly argue that this sink falls into this category. Now back to where I started. In my applications I am configuring Serilog to use the UDP sink when the code has been built in `DEBUG`. That way I can watch the log event roll by in Log2Console while debugging the application.

If the application isn't build in `DEBUG` I configure Serilog to use this sink, because then the log events are sent to the Elastic Stack.

Would that solve your problem?

**Comment by Dissimilis** [comment]
Log2Console is new to me, thanks for introducing, I will definitely look into it. But this is a topic for discussion about logging in general and I don't think it has a place here :( Do you know where we could do it?

Currently I am trying to solve the problem at hand without braking my team's flow. The problem is: "_different objects with same property names_". I will try to formulate solution in line with your vision:

> I am against adding formatters that doesn't fit a common use case

Common case is sending events to Logstash and then to ELK. When doing microservices, it is easy for different people to use same name for differently structured properties and end up with problem I described initial.
Your solution is to use namespace for all properties. I propose to extend this, and allow to use namespaces only for properties passed directly while calling logger. 
Reasoning would be: enrichers are lot easier to control than individual events and there is a strong case to have enrichments with unified names across services. And mostly there is no needed to keep same naming for event properties from different services.
Formatted event example:
```
{ 
"messageTemplate": "Event happened with item {@Item}",
"Properties": {
	"MyServiceX.Item": {<..>},
	"MachineName" : "XA4561",
	"CorrelationId": "1234567890"
}}
```
Does that sound like something worth providing for all users?

**Comment by FantasticFiasco** [comment]
I need some days to think about this issue, and investigate what the possibilities are with the log event and its properties. Your proposal is a sound one and something I will consider.

**Comment by FantasticFiasco** [comment]
I think what you propose is a good idea and something I should implement, unless you are eager to contribute (I don't mind doing it, I think it will increase the value of the sink).

I think we should create two new event formatters called `NamespacedRenderedTextFormatter` and `NamespacedTextFormatter`. Either we place this namespace as a sub-property of `Properties` as you propose or place it directly in the document root alongside `Properties`.

As you mention in your other issue, `Serilog.Sinks.Console` has implemented filtering of properties not being rendered in the message [here](https://github.com/serilog/serilog-sinks-console/blob/dev/src/Serilog.Sinks.Console/Sinks/SystemConsole/Output/PropertiesTokenRenderer.cs), we can surely be inspired by that code.

What do you think?

**Comment by Dissimilis** [comment]
I would prefer single formatter with a constructor parameter indicating whether I want to put rendered parameters in a namespace. But two formatters may align better with what you have now.
Namespace as sub-property sounds better to me.

Please explain more how these formatters would work. Will I be able to do following?:
Omit rendered properties altogether;
Have rendered properties in a different namespace as non rendered properties;
Have non rendered properties without namespace and rendered ones with namespace (and vice versa);
Control namespace of non rendered but directly passed properties (`Log.Error("Msg",CustomObj)`)

**Comment by FantasticFiasco** [comment]
The formatter is required to have a default constructor if used in combination with [Serilog.Settings.Configuration](https://github.com/serilog/serilog-settings-configuration), that's why we have to create two different formatters.

> - Omit rendered properties altogether;

No, all properties will in some form be a part of the serialized JSON

> -Have rendered properties in a different namespace as non rendered properties;

Yes, rendered properties will be namespaced while the rest will be as they already are today, placed directly under `Properties`

> - Have non rendered properties without namespace and rendered ones with namespace (and vice versa);

Exactly

> - Control namespace of non rendered but directly passed properties (Log.Error("Msg",CustomObj))

The custom object is not a part of the message template and will because of this be classified as a enriched property, and placed directly in `Properties`

**Comment by FantasticFiasco** [comment]
A pre-release has been [uploaded to nuget.org](https://www.nuget.org/packages/Serilog.Sinks.Http/4.3.0-namespaced-formatter-00675). Please verify that it behaves as expected.

**Comment by Dissimilis** [comment]
I'm confused why NamespacedTextFormatter is abstract?
Otherwise it works as we discussed. But sadly it can't add namespace to non-rendered properties.  Which defeats the namespace purpose somewhat.  `Log.Error("Msg",CustomObj)` would appear as "__1" and can contain mixed types.

**Comment by FantasticFiasco** [comment]
> I'm confused why NamespacedTextFormatter is abstract?

A default value on the namespace would not only defeat the purpose of the formatter, it would also mislead teams into using the same namespace, when in fact they should have created their own. By making the formatter abstract I am enforcing the developer to chose a namespace, providing a [pit of success](https://english.stackexchange.com/questions/77535/what-does-falling-into-the-pit-of-success-mean).

> But sadly it can't add namespace to non-rendered properties.

Well you cannot have both. You cannot have enriched properties outside the namespace and properties supplied in the logging statement (but not being part of the message template) within the namespace. From the perspective of the log event there is no difference. And yes, you've argued that one could provide a predicate that either place the property inside or outside of the namespace, but I have a hard time figuring out how that predicate would have been constructed to cover all cases. I think this is an acceptable middle ground, that still provide value in some circumstances.

If you don't have any more objections I'll get this ready for an official release. Thank you for your input, and the time you've invested in this, and your other issues!

A final note, instead of writing `Log.Error("Msg",CustomObj)` one could write `Log.ForContext("customObj", CustomObj).Error("Msg")`. It better demonstrate the purpose of `CustomObj` in my humble opinion.

**Comment by Dissimilis** [comment]
> A default value on the namespace would not only defeat the purpose of the formatter
Sure, but I'm not suggesting default value. I fail to see how abstract class is related to default namespace name. 
If developer uses `NamespacedTextFormatter` without namespace (`if string.IsNullOrEmpty`), exception should be thrown. 
Forcing to create new class to be able to set namespace name is quite strange behavior, which I cannot agree with.

**Comment by FantasticFiasco** [comment]
An official version has now been published on www.nuget.org.
