### ISSUE TITLE
Provide the ability to prevent sending properties that do appears in template

### ISSUE THREAD

**Issue by Dissimilis** [FantasticFiasco/serilog-sinks-http#40]
Serilog Console output template has this:
`{Properties}` - All event property values that don't appear elsewhere in the output.
We need this functionality in Http sink, to prevent sending unneeded properties used only for message formatting.
This would prevent flooding recipients with redundant data.
 
Example usage:
```
var logger = new LoggerConfiguration()	
.WriteTo.Http("http://url", sendOnlyUnusedProperties = true)
.CreateLogger();

//This would send only otherData through http, id would not be sent because it is in message itself
logger.Information("Received: {id}", id, otherData);
```

**Comment by FantasticFiasco** [comment]
I see this issue from another perspective.

Output templates are almost always used when you don't want the log event as structured data, but instead as human readable text. That's why you most often see them in sinks that render the log event, as the console sink you mention or my [UDP sink](https://github.com/FantasticFiasco/serilog-sinks-udp).

The use case of displaying the log event as human readable text does not, according to me, fit this sink. This sink is all about transporting the log event to a recipient. It is the responsibility of the recipient to make this log event searchable, readable and everything else you would like from it.

Lets continue to talk about the redundant data, or what some might call the non-normalized data. It is true the the default event formatter has redundant data, but that is because of the rendered message, not because of the structured properties. This sink comes pre-packed with two normalized event formatters and they are called `NormalTextFormatter` and `CompactTextFormatter`. They are sending the log event with the _message template_ and all its properties, but not the rendered message. They are pushing the responsibility of rendering the message to the recipient, which in some cases is perfectly fine, for instance if the event is sent from a constrained environment.

I think this is what I am trying to emphasize: _the properties are more important than the rendered message_. Not all properties are part of the message template, but they still provide enormous value (see [enrichments](https://github.com/serilog/serilog/wiki/Enrichment) for examples). You most often search using the properties, and you always build dashboards and visualizations using the properties, never the rendered message. The message is nice to have, but nothing more.

**Comment by Dissimilis** [comment]
Looks like everything you said is true. But it is also sounds like opinionated view. 
This sink is called `Serilog.Sinks.Http`, not `Serilog.Sinks.StructuredHttp`. I expect to use it as a transport sink and bend to my use case.   I can do that now by implementing my own EventFormatter, but it would be nice to have more customization options, which wouldn't change idea behind this sink. Sometimes only simple transformations are needed, and supplying own `Func<>` to formatter might be superior to writing own formatter from scratch. Would you be interested in expanding formatters (adding more/customizing existing ones), or you are against that?

Back to my suggestion. Not all http receivers are as smart as Logstash, sometimes we want to control content coming from sender. But event with a Logstash it is difficult to distinguish between properties existing in a message and external properties from enrichers. Receiver would have to parse the template and then correlate placeholders with property names to filter them out. But it is easy for EventFormatter to do. 

>the properties are more important than the rendered message

IMHO it depends. Sometimes this is true, but sometimes other things are more important. Http sink can accommodate both of those needs without  braking it's vision or adding complexity.  Please consider other use cases, than just sending events to ELK for dashboards, and please be open minded about pull requests for including other interesting EventFormatters :)

**Comment by FantasticFiasco** [comment]
> Looks like everything you said is true. But it is also sounds like opinionated view.

It most certainly is. I am a man of opinions, and I usually stick to them :-)

As I mentioned in #39 I think this sink would be categorized as a sink that fits applications running in production, and does little to help debugging code in development.

> Would you be interested in expanding formatters (adding more/customizing existing ones), or you are against that?

I am against adding formatters that doesn't fit a common use case. If you would say to be: "I am using this awesome log event receiver, and a whole other bunch of applications are using it, but it requires the log events the be structured in a certain way", then I would be happy to provide you the formatter. But as it is now, I don't see any major benefits with providing a multitude of formatters, especially when it is so easy to write your own formatter.

I would recommend you to write a event formatter that fits the needs of your product, and distribute that formatter internally at your company using private NuGet feeds. Wouldn't that solve your problem?

**Comment by Dissimilis** [comment]
Using own event formatter would solve the problem, I just wanted this sink to do more trivial things, and not be just barebones for implementing your own formatters.
With that I rest my case. Thanks for your time.
