### ISSUE TITLE
Possible additional functionality

### ISSUE THREAD

**Issue by smasherprog** [FantasticFiasco/serilog-sinks-http#44]
Is it possible to make the library create its own instance of the IhttpClient?
You could take a string to the concrete implementation and use reflection to find and instantiate the client.
This way, you can allow users to write their own Ihttpclient implementation and use 
https://github.com/serilog/serilog-settings-configuration
 ReadFrom.Configuration(configuration)

As it stands, I want to Write to a Debug Sink in development, but write to the http sink in production and I also need to create my own httpclient because I need to specify authentication.

**Comment by FantasticFiasco** [comment]
Hi smasherprog and welcome!

The sink already supports custom HTTP clients, both declared in code but also declared using [Serilog.Settings.Configuration](https://github.com/serilog/serilog-settings-configuration), or at least that is what [my tests tell me](https://github.com/FantasticFiasco/serilog-sinks-http/blob/master/test/Serilog.Sinks.HttpTests/appsettings_http.json).

The only downside to Serilog.Settings.Configuration is that it has no notion of any dependency injection container. The type defined will have to have a default constructor since it is created using reflection.

**Comment by smasherprog** [comment]
Awesome, I didnt see that you had that functionality!
