### ISSUE TITLE
Rolling file sink question

### ISSUE THREAD

**Issue by sachabarber** [FantasticFiasco/serilog-sinks-http#66]
So this is more of a question than an issue, but we could really do with an answer to this. So the question is this

# DurableHttpSink use of Rolling File Sink
So I know the `DurableHttpSink` uses `RollingFileSink` internally. I just wanted to know if the `DurableHttpSink` is intelligent enough to only write log entries to the rolling file sink when there is no connectivity to the HTTP endpoint, or does it just write every log entry it has seen to the rolling file sink files no matter what the state of the HTTP endpoint

I mean based on these lines in the **DurableHttpSink** source code, pretty sure the answer is ALL items get written to disk no matter what.

```
/// <summary>
/// Initializes a new instance of the <see cref="DurableHttpSink"/> class.
/// </summary>
public DurableHttpSink(
	string requestUri,
	string bufferPathFormat,
	long? bufferFileSizeLimitBytes,
	int? retainedBufferFileCountLimit,
	int batchPostingLimit,
	TimeSpan period,
	ITextFormatter textFormatter,
	IBatchFormatter batchFormatter,
	IHttpClient client)
{
	if (bufferFileSizeLimitBytes.HasValue && bufferFileSizeLimitBytes < 0)
		throw new ArgumentOutOfRangeException(nameof(bufferFileSizeLimitBytes), "Negative value provided; file size limit must be non-negative.");

	shipper = new HttpLogShipper(
		client,
		requestUri,
		bufferPathFormat,
		batchPostingLimit,
		period,
		batchFormatter);

	sink = new RollingFileSink(
		bufferPathFormat,
		textFormatter,
		bufferFileSizeLimitBytes,
		retainedBufferFileCountLimit,
		Encoding.UTF8);
}

/// <summary>
/// Emit the provided log event to the sink.
/// </summary>
public void Emit(LogEvent logEvent) =>
	sink.Emit(logEvent);
```

Is there no possibility to change how this works, such that if the HTTP endpoint is alive and well, nothing is written to the rolling sink buffer files. And the `HttpLogShipper` could ultimately decide if the endpoint is not healthy ONLY then should it start storing stuff in the rolling sink buffer files

I would love to know your thoughts on this

My own thoughts are it would drastically reduce the size of the maintained files on disk

**Comment by FantasticFiasco** [comment]
Hi again!

To reduce the risk of misunderstanding, the durability nature of the sink has nothing to do with the log event receiver but instead your own process. If your process for some reason is terminated, the log events yet not transported to the receiver gets a new chance when your process is restarted. Both variants of the HTTP sink support the case where the log receiver can be unresponsive, i.e. a log event is not dropped just because the receiver is unable to receive it. If you are fine with fire and forget, you can take a look at my [UDP sink](https://github.com/FantasticFiasco/serilog-sinks-udp).

You are correct in your conclusion that all log events first are persisted to disk, even if we know that the receiver is responsive (which in itself is a statement that is problematic to back up, networks fail, that is the norm). The reason for persisting log events to disk is to reduce the time a log event is held in memory, i.e. reduce the risk of losing the event given that your process is terminated.

Some time after the log events have been persisted to disk, depending on your configuration of the sink, the log event shipper picks up the log events and transports them over the network.

It boils down to whether you can accept that log events sometimes are being lost. If you wan't to minimize the risk of losing log events you use the durable sink, but if you are willing to lose logs given your process being terminated, or would be unable to restart with access to the persisted log events, you can use the non-durable sink.

From my perspective, persisting log events to disk is a good solution to reduce the risk of losing them, but I am eager to hear your view on it. Would you have implemented it differently?

**Comment by sachabarber** [comment]
I think what I would have done is make that a concern of the final part of the pipeline, that does the dispatch to the HTTP Endpoint. of that is down then I would have written the log files.

But i understand your reasoning. 

I'll close the ticket as its more a question

**Comment by FantasticFiasco** [comment]
I am sorry that you have to invest energy into this piece of code, that it doesn't behave according to your assumptions. I would much rather having this to "just work", and let you focus on your business problems. :-(

Again, if you have any other questions I am happy to try to answer them.
