### ISSUE TITLE
Durable file size rolled HTTP sink not sink to API properly

### ISSUE THREAD

**Issue by manjunathdl66** [FantasticFiasco/serilog-sinks-http#74]
I am trying to implement Durable file size rolled HTTP sink in my .net core api.
Below is the configuration i have done
 "Serilog": {
    "MinimumLevel": "Verbose",
    "WriteTo": [
      {
        "Name": "DurableHttpUsingFileSizeRolledBuffers",
        "Args": {
          "requestUri": "http://localhost:19709/api/LogEvents/log-events",
          "httpClient": "Order.API.LogSink.CustomHttpSink, Order.API",
          "bufferBaseFileName": "C:\\Temp\\serilog-configuration-.json", 
          "bufferFileSizeLimitBytes": null,
          "retainedBufferFileCountLimit": 31,
          "batchPostingLimit": 100,
          "period": "00:00:00.001"
        }
      }
    ]
  }
I am trying to log 100 times in my api but its sinking only 2 logs to my request uri.
And it will create the below files in my temp folder

![image](https://user-images.githubusercontent.com/16134705/57599664-1a0a0b00-7575-11e9-9bdb-aee9e2477bdf.png)

But in the Bookmark file only first file information will be exists
575:::C:\Temp\serilog-configuration.json-20190513.json and it will sink only this file logs.

Can some one help me out for proper configuration so that it should sink all the inforation to my endpoint api.

**Comment by manjunathdl66** [comment]
And also could you  please help for what are all the dependent Nuget Packages to add for this to work.

**Comment by FantasticFiasco** [comment]
> Can some one help me out for proper configuration so that it should sink all the inforation to my endpoint api.

I'll try to recreate your issue tonight. If you have a sample application I could run to verify your problem it would reduce the time it takes for me to solve your issue.

> And also could you please help for what are all the dependent Nuget Packages to add for this to work.

The dependencies of this package is for storing the log events on disk before sending them over the network, i.e. the durable nature of the sink, as well as batching to be able so send many events in one HTTP request. But you don't have to add them yourself since they are transient dependencies of this package.

**Comment by FantasticFiasco** [comment]
There are a couple of things I would change in your configuration.

- `bufferBaseFileName` - I would change it to `C:\Temp\serilog-configuration` because it is the base name, or prefix, of the buffer files. See [wiki](https://github.com/FantasticFiasco/serilog-sinks-http/wiki/Durable-file-size-rolled-HTTP-sink#arguments) for further information.
- Setting `retainedBufferFileCountLimit` when you set `bufferFileSizeLimitBytes` to `null` has no effect. You will never roll to a new file since the first will grow indefinitely. Growing indefinitely is problematic if your process is a long running process, but I guess it isn't?
- `period` is to low. Are you sure you wish to send a request that often?

Another developer reported that some log events didn't reach the log server, but it was because he [ran a console application that terminated before the log events where sent](https://github.com/FantasticFiasco/serilog-sinks-http/issues/72#issuecomment-479627143). Perhaps that is your issue as well?

**Comment by FantasticFiasco** [comment]
I've modified [serilog-sinks-http-sample-dotnet-core](https://github.com/FantasticFiasco/serilog-sinks-http-sample-dotnet-core) locally according to your specific configuration, but am not experiencing your issue. All log events reach the log server, and only one buffer file is created.

Could you please fork [serilog-sinks-http-sample-dotnet-core](https://github.com/FantasticFiasco/serilog-sinks-http-sample-dotnet-core) and try to recreate your issue there? It would be much easier if we could work with the same sample application in our pursuit of the issue you are describing.

The ball is in your court.

**Comment by manjunathdl66** [comment]
Hey this issue got fixed and now i am able to generate log and also sink to service. Thank you so much for your time and the solution.
The issue was every time i was creating the object of ILogger. Now i have changed to Singleton after that its started working.
If Possible can you please help me the below issue.
Object of type 'LoggerClient.CustomSink.CustomHttpSink' cannot be converted to type 'Serilog.Sinks.Http.IHttpClient'.'
When i created the Logger in separate Class Library. Configuration is attached above.

**Comment by FantasticFiasco** [comment]
This comes down to reflection. Make sure that the file `Order.API.dll` exists in the output directory of your new class library. I cannot help you more without a sample application.

**Comment by manjunathdl66** [comment]
Could you please elaborate "Make sure that the file Order.API.dll exists in the output directory of your new class library"

**Comment by FantasticFiasco** [comment]
I've looked at your code, and it has nothing to do with this particular sink. I would encourage you to read up on Serilog, or ask a question on their Gitter channel. In any case, I think we can close this issue.

Best of luck going forward!

**Comment by manjunathdl66** [comment]
Hey below is the configuration settings for the above attached code 
  "Serilog": {
    "MinimumLevel": "Verbose",
    "WriteTo": [
      {
        "Name": "DurableHttpUsingFileSizeRolledBuffers",
        "Args": {
          "requestUri": "http://localhost:19709/api/LogEvents/log-events",
          "httpClient": "My.LoggerClient.CustomSink.CustomHttpSink, My.LoggerClient",
          "bufferBaseFileName": "C:\\Temp\\Catalog\\catalog-configuration.json", //"%TEMP%\\Logs\\serilog-configuration-sample.json",
          "bufferFileSizeLimitBytes": 1000,
          "retainedBufferFileCountLimit": 2,
          "batchPostingLimit": 100,
          "period": "00:00:10.000"
        }
      }
    ]
  }

I am facing the below issue
**Object of type 'My.LoggerClient.CustomSink.CustomHttpSink' cannot be converted to type 'Serilog.Sinks.Http.IHttpClient'.'**
